#!/usr/bin/env python3
"""build_index.py — generate catalog/INDEX.md: every component with its
'when to use' description, extracted from each asset's own frontmatter.

Re-run after sync_upstream.py / build_manifest.py.
"""

import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAT = ROOT / "catalog"
sys.path.insert(0, str(Path(__file__).resolve().parent))
from install import parse_frontmatter, discover

MAX_DESC = 220

def desc_of(a):
    p = a["path"]
    try:
        if a["type"] == "skill":
            fm, _ = parse_frontmatter((p / "SKILL.md").read_text(encoding="utf-8"))
        elif a["type"] == "mcp":
            d = json.loads(p.read_text(encoding="utf-8"))
            srv = next(iter(d.get("mcpServers", d).values()), {})
            return d.get("description") or srv.get("description", "") or ""
        else:
            fm, _ = parse_frontmatter(p.read_text(encoding="utf-8"))
        d = re.sub(r"\s+", " ", str(fm.get("description", ""))).strip()
        # trim ECC-style "Use this agent when..." boilerplate lead
        d = re.sub(r"^Use this (agent|command|skill) (when|for|to)\s*", "", d, flags=re.I)
        d = re.sub(r"^Invok(e|ing?)\s+(this\s+)?(agent\s+)?(when|for)\s*", "", d, flags=re.I)
        if not d:
            return "—"
        return d[:MAX_DESC].rstrip() + ("…" if len(d) > MAX_DESC else "")
    except Exception:
        return "—"

def table(assets):
    rows = ["| Component | When to use |", "| --- | --- |"]
    for a in assets:
        rows.append(f'| `{a["name"]}` | {desc_of(a).replace("|", "\\|")} |')
    return "\n".join(rows)

def main():
    assets = discover()
    by = {}
    for a in assets:
        by.setdefault((a["source"], a["type"]), []).append(a)

    out = ["# Component Index — what each asset does and when to use it",
           "",
           "Auto-generated by `scripts/build_index.py` from each component's own",
           "`description` frontmatter. Regenerate after `sync_upstream.py`.",
           "Categories marked *(n)* show component counts.",
           ""]
    order = [("mp", "skill", "mattpocock skills"), ("imp", "skill", "Impeccable design"),
             ("ecc", "skill", "ECC skills"),
             ("ecc", "agent", "ECC sub-agents"), ("ecc", "command", "ECC commands"),
             ("ecc", "mcp", "ECC MCP servers")]
    for src, t, title in order:
        group = by.get((src, t), [])
        cats = {}
        for a in group:
            cats.setdefault(a["category"], []).append(a)
        out += [f"\n## {title} ({len(group)})\n"]
        for cat in sorted(cats):
            out += [f"\n### {cat} *({len(cats[cat])})*\n", table(sorted(cats[cat], key=lambda x: x["name"]))]
    dest = CAT / "INDEX.md"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"INDEX.md: {len(assets)} entries, {dest.stat().st_size//1024} KB")

if __name__ == "__main__":
    main()
